[package]
name = "azure"
version = "0.18.0"
authors = ["The Servo Project Developers"]
documentation = "http://doc.servo.org/azure/"
repository = "https://github.com/servo/rust-azure"
description = "Bindings to Mozilla's Moz2D library"
license = "MPL-2.0"

build = "build.rs"

[features]
default = []
plugins = ["serde", "serde_derive", "heapsize", "heapsize_derive"]

[build-dependencies]
cmake = "0.1"

[dependencies]
euclid = "0.14"
heapsize = {version = "0.4", optional = true}
heapsize_derive = {version = "0.1.0", optional = true}
libc = "0.2"
serde = {version = "1.0", optional = true}
serde_derive = {version = "1.0", optional = true}
servo-skia = "0.30000005.3"

[target.'cfg(all(target_os = "linux", target_os = "android"))'.dependencies]
freetype = "0.2"
servo-freetype-sys = "4.0.1"

[target.'cfg(target_os = "linux")'.dependencies]
x11 = { version = "2.0.0", features = ["xlib"] }

[target.'cfg(target_os = "android")'.dependencies]
servo-egl = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.3"
core-graphics = "0.8"
core-text = "5.0"
